[package]
name = "backend"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
axum = { version = "0.7.9", features = ["macros"] }
dotenvy = { git = "https://github.com/allan2/dotenvy", version = "0.15.7", features = ["macros"] }
shuttle-axum = "0.49.0"
shuttle-runtime = "0.49.0"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["normalize-path", "fs"] }
